### ISSUE TITLE
安装的时候有问题

### ISSUE THREAD

**Issue by odinyu** [YouYII/EasyReader#2]
- yargs-parser@4.2.1 node_modules/react-native-vector-icons/node_modules/yargs-parser
- yargs@6.6.0 node_modules/react-native-vector-icons/node_modules/yargs
NovelReader@1.3.1 /Users/Odin/Desktop/react/EasyReader
├── react@15.3.2
└── UNMET PEER DEPENDENCY react-native-vector-icons@2.1.0

npm WARN react-native-elements@0.6.4 requires a peer of react-native-vector-icons@~3.0.0 but none was installed.
npm WARN react-native@0.41.2 requires a peer of react@~15.4.0 but none was installed.

然后我把react-native-vector-icons改成~3.0.0
NovelReader@1.3.1 /Users/Odin/Desktop/react/EasyReader
└─┬ react-native-vector-icons@3.0.0
  └─┬ yargs@6.6.0
    └── yargs-parser@4.2.1

npm WARN react-native@0.41.2 requires a peer of react@~15.4.0 but none was installed.

这个要怎么解决？谢谢！

**Comment by Yi-Z0** [comment]
暂时没有适配新版本的 RN , 你不要升级 RN 再试试呢
