### ISSUE TITLE
怎么确定一页显示多少文字？

### ISSUE THREAD

**Issue by mylesshie** [YouYII/EasyReader#3]
你好，请问您是怎么确定一页显示多少字符的呢？字符里面包含了换行符元素的

**Comment by Yi-Z0** [comment]
使用 https://github.com/YouYII/EasyReader/blob/master/src/containers/Reader/Reader.js (滚动翻页)
代替
https://github.com/YouYII/EasyReader/blob/master/src/containers/Reader.js (无动画的左右翻页)
